name: CD

on:
  push:
    branches:
      - "master"

concurrency:
  group: "pages"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save .env file
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        shell: bash
        run: |
          echo "$ENV_FILE_CONTENT" > .env

      - name: Add git commit hash to .env file
        run: echo -e "\nVITE_VERSION=$(git rev-parse --short HEAD)" >> .env

      - name: Build the app
        run: make prod_build_bundle

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
